# Generated by Django 3.0.1 on 2020-12-14 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_default', models.CharField(blank=True, max_length=50, null=True)),
                ('email_default', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number_default', models.CharField(blank=True, max_length=20, null=True)),
                ('country_default', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city_default', models.CharField(blank=True, max_length=40, null=True)),
                ('address_default', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode_default', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
