# Generated by Django 3.0.1 on 2020-12-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_default',
            new_name='address_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city_default',
            new_name='city_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country_default',
            new_name='country_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_default',
            new_name='email_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name_default',
            new_name='full_name_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number_default',
            new_name='phone_number_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postcode_default',
            new_name='postcode_profile',
        ),
    ]
