# Generated by Django 3.0.1 on 2020-12-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201207_2135'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='ProductOrder',
        ),
    ]
