# Generated by Django 3.0.1 on 2020-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default='', max_length=254),
        ),
    ]
