# Generated by Django 3.0.1 on 2020-12-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201219_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclusive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
